---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
spec:
  template:
    spec:
      containers:
      - args:
        - --postgres-restore
        env:
        - name: BACKUP_FILE
          value: mysql-server.mysql-3306-all-20200101001200/test_db.sql
        - name: DB_NAME
          value: test_db
        - name: HOST
          value: mysql-server.mysql
        - name: PASSWORD
          value: password
        image: sjdaws/backup-restore-db
        imagePullPolicy: Always
        name: backup
        volumeMounts:
        - mountPath: /backup
          name: backup
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /home/mysql-backups
          type: Directory
        name: backup
